In [22]:
nums= list(map(int,input().split()))
n=nums[0]
m=nums[1]
thickness=int(n/2)
c='.|.'
print(n,m,thickness,c)
p=int(m/2)
for i in range(thickness):
    print((c * i).rjust(p-1,'-') + c + (c * i).ljust(p-1,'-'))
print("WELCOME".center(m,'-'))
for i in range(thickness):
    print((c *(thickness-i-1)).rjust(p-1,'-') + c + (c *(thickness-i-1)).ljust(p-1,'-'))

9 27
9 27 4 .|.
------------.|.------------
---------.|..|..|.---------
------.|..|..|..|..|.------
---.|..|..|..|..|..|..|.---
----------WELCOME----------
---.|..|..|..|..|..|..|.---
------.|..|..|..|..|.------
---------.|..|..|.---------
------------.|.------------


In [23]:
str="hello{}"
print(str.format(" sumit"))

hellosumit


In [37]:
number=int(input())
for i in range(1,number+1):
    print("{0:{1}d} {0:{1}o} {0:{1}X} {0:{1}b}".format(i,len("{0:b}".format(number))))

20
    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001
   18    22    12 10010
   19    23    13 10011
   20    24    14 10100


In [2]:
import string
size=int(input())
alphabet=string.ascii_lowercase
print(alphabet)


4
abcdefghijklmnopqrstuvwxyz


In [1]:
import numpy as np
array = np.array(list(map(int, input().split())))
print(array.reshape(3, 3))


5 6 9 6 4 7 2 3 54
[[ 5  6  9]
 [ 6  4  7]
 [ 2  3 54]]


In [3]:
from itertools import combinations

N,l,K = int(input()),input().split(),int(input())
c_list = combinations(l,K)
count_a = 0
total_c = 0 
for c in c_list:
    count_a += 1 if 'a' in c else 0
    total_c +=1

print(count_a/total_c)


4
a a c d
2
0.8333333333333334
