In [2]:
#remove dublicates
d=['a','b','v','a','b','e']
l=list(dict.fromkeys(d))
print(l)

['a', 'b', 'v', 'e']


In [3]:
# remove dublicates
txt="sumit sharma is bad guy"
print(txt[::-1])

yug dab si amrahs timus


In [4]:
#no of characters together
import textwrap

a="drftgyiuoioitytdfghjiitfdtdfghkjlhfdszxdgjhkjmlhfdsdfhgjhkjfdszxcvbhkjuit"
width=5
print(textwrap.fill(a,width))

drftg
yiuoi
oityt
dfghj
iitfd
tdfgh
kjlhf
dszxd
gjhkj
mlhfd
sdfhg
jhkjf
dszxc
vbhkj
uit


In [13]:
# print decimal , hxa,binary,octal together

n=int(input())
for i in range(n):
    print("{0:{1}} {0:{1}o} {0:{1}x} {0:{1}b}")
    
for i in range(n):
    print("{0:{1}} {0:{1}o} {0:{1}x} {0:{1}b}".format(i,len("{0:b}".format(n))))

6
{0:{1}} {0:{1}o} {0:{1}x} {0:{1}b}
{0:{1}} {0:{1}o} {0:{1}x} {0:{1}b}
{0:{1}} {0:{1}o} {0:{1}x} {0:{1}b}
{0:{1}} {0:{1}o} {0:{1}x} {0:{1}b}
{0:{1}} {0:{1}o} {0:{1}x} {0:{1}b}
{0:{1}} {0:{1}o} {0:{1}x} {0:{1}b}
  0   0   0   0
  1   1   1   1
  2   2   2  10
  3   3   3  11
  4   4   4 100
  5   5   5 101


In [15]:
# capitalising first letter
s="sumit kumar is duffer boy, he is a loosser"
s1=s[0].upper()

for i in range(1,len(s)):
    if s[i-1]==" ":
        s1=s1+s[i].upper()
    else:
        s1=s1+s[i]

print(s1)

Sumit Kumar Is Duffer Boy, He Is A Loosser


In [23]:
# remove consecutive iteration and wrap it to 2
s1='AABCAAADA'
k=2
from collections import OrderedDict
ls=[s1[i:i+k] for i in range(0,len(s1),k)]
print(ls)

['AA', 'BC', 'AA', 'AD', 'A']


In [36]:
ss=''
for str in ls:
    ss=ss+"".join(OrderedDict.fromkeys(str))
    print("".join(OrderedDict.fromkeys(str)))
    
print(ss)
print(textwrap.fill(ss,k))

A
BC
A
AD
A
ABCAADA
AB
CA
AD
A


In [34]:
import numpy
#arr=numpy.array([[1,2],[3,4]])
a,b=map(int,input().split())
arr=numpy.array(list(input().split() for _ in range(a)),int)
print(arr)
print(numpy.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3 4]


In [43]:
# list comprehension
x,y,z=map(int,input().split())
n=3
lst=[[a,b,x] for a in range(x+1) for b in range(y+1) for c in range(z+1) if a+b+c!=n]
print(lst)


1 1 1
[[0, 0, 1], [0, 0, 1], [0, 1, 1], [0, 1, 1], [1, 0, 1], [1, 0, 1], [1, 1, 1]]


In [44]:
# find runnerup score
n=input()
arr=list(set(map(int , input().split())))
arr.sort()
n=-2
print(arr[n])

5 
12 12 45 78 9
45


In [116]:
# frequency of character in string
txt='fdftuipopitrtedxfhcvlh;joutytfcvhjbxzsaqazzaqwertyuikjhbvfcdxscvbnmmlpoiuytfredwazxcvbhnjmk'
#use count function
for char in range(len(txt)):
    counter=txt.count(txt[char])
    print(txt[char],counter,sep=' ',end=" | ")
    
txt1=list(dict.fromkeys(txt))
print(txt1,counter)
print("_"*100)

#Collection
from collections import Counter
mylist=[]
mylist.extend("fdftuipopitrtedxfhcvlh;joutytfcvhjbxzsaqazzaqwertyuikjhbvfcdxscvbnmmlpoiuytfredwazxcvbhnjmk")
print(Counter(mylist))

f 6 | d 4 | f 6 | t 7 | u 4 | i 4 | p 3 | o 3 | p 3 | i 4 | t 7 | r 3 | t 7 | e 3 | d 4 | x 4 | f 6 | h 5 | c 5 | v 5 | l 2 | h 5 | ; 1 | j 4 | o 3 | u 4 | t 7 | y 3 | t 7 | f 6 | c 5 | v 5 | h 5 | j 4 | b 4 | x 4 | z 4 | s 2 | a 4 | q 2 | a 4 | z 4 | z 4 | a 4 | q 2 | w 2 | e 3 | r 3 | t 7 | y 3 | u 4 | i 4 | k 2 | j 4 | h 5 | b 4 | v 5 | f 6 | c 5 | d 4 | x 4 | s 2 | c 5 | v 5 | b 4 | n 2 | m 3 | m 3 | l 2 | p 3 | o 3 | i 4 | u 4 | y 3 | t 7 | f 6 | r 3 | e 3 | d 4 | w 2 | a 4 | z 4 | x 4 | c 5 | v 5 | b 4 | h 5 | n 2 | j 4 | m 3 | k 2 | ['f', 'd', 't', 'u', 'i', 'p', 'o', 'r', 'e', 'x', 'h', 'c', 'v', 'l', ';', 'j', 'y', 'b', 'z', 's', 'a', 'q', 'w', 'k', 'n', 'm'] 2
____________________________________________________________________________________________________
Counter({'t': 7, 'f': 6, 'h': 5, 'c': 5, 'v': 5, 'd': 4, 'u': 4, 'i': 4, 'x': 4, 'j': 4, 'b': 4, 'z': 4, 'a': 4, 'p': 3, 'o': 3, 'r': 3, 'e': 3, 'y': 3, 'm': 3, 'l': 2, 's': 2, 'q': 2, 'w': 2, 'k': 2, 'n': 2, ';': 1})


In [60]:
import math
print(math.sqrt(16))
l=[23,46,78,98,654,9]
print(max(l))
print(min(l))
print(math.ceil(3.8))
print(math.factorial(5))
print(math.sin(90))
print(math.cos(90))
print(math.tan(90))
eval(input(5*4*9+4))

4.0
654
9
4
120
0.8939966636005579
-0.4480736161291701
-1.995200412208242
18457+65+76+7*654/3


1724.0

In [68]:
#string format
a,b,c=10,20,30
print("{x} {y} {z}".format(x=a,y=b,z=c))
print("{} {} {}".format(a,b,c)) # replacement operator
s='sumit'
f=6.7
print('%i %d %f %s'%(a,b,f,s))

10 20 30
10 20 30
10 20 6.700000 sumit


In [69]:
# pattern 1
for i in range(int(input())):
    print("*"*i)

5

*
**
***
****


In [73]:
# pattern2
n=int(input())
for i in range(n):
    print(' '* (n-i),end=" ")
    print('* '*i)

5
      
     * 
    * * 
   * * * 
  * * * * 


In [76]:
# regular Expression
import re
p=re.compile('ab')
matcher=re.finditer(p,'abaaabbbababbaaababbbbbbbbaaaabab')
#matcher=p.finditer('abaaabbbababbaaababbbbbbbbaaaabab')
print(matcher)

for m in matcher:
    print(m.start(),m.end(),m.group(),sep=' ')

0 2 ab
4 6 ab
8 10 ab
10 12 ab
15 17 ab
17 19 ab
29 31 ab
31 33 ab


In [82]:
s='sumit'
m=re.match(s,'sumit is boy or girl ??') # match target only at begining of target string... 
if m != None:
    print(m.start(),m.end(),sep=" ")
    

s2='jay'
m1=re.fullmatch(s2,'jay') #full target
if m != None:
    print("matched")
else:
    print("not matched")


0 5
matched


In [87]:
ss=input()
mm=re.search(ss,'aeiou st') # search first occurance
if mm != None:
    print(mm.start(),mm.end(),sep=" ")


ae
0 2


In [90]:

l=re.findall('[0-9]','abuh5thjj877tyvhj88vhjjjh9')
print(l)

l=re.findall('[0-9]+','abuh5thjj877tyvhj88vhjjjh9')
print(l)

['5', '8', '7', '7', '8', '8', '9']
['5', '877', '88', '9']


In [94]:
st=re.sub('[0-9]+','#','abuh5thjj877tyvhj88vhjjjh9')
print(st)
st=re.subn('[0-9]+','#','abuh5thjj877tyvhj88vhjjjh9')
print(st)#also return no of substitution
st=re.split('[0-9]+','abuh5thjj877tyvhj88vhjjjh9')
print(st)#also return no of substitution

abuh#thjj#tyvhj#vhjjjh#
('abuh#thjj#tyvhj#vhjjjh#', 4)
['abuh', 'thjj', 'tyvhj', 'vhjjjh', '']


In [ ]:
# re.fullmatch() or findall()
mbno='[6-9]\d{9}'
mbno='[6-9][0-9]{9}'
aadharvalidation='\d{12}'
mail='[\w[a-zA-Z0-9.]@(gmail|redit|mail)[.][a-z]{2,3}]'
gmail='[\w[a-zA-Z0-9]@mail[.]com]'

In [96]:
#itertools
from itertools import product 
A=[1,2,3]
print(*A)

1 2 3


In [99]:
x=list(map(int,input().split()))
y=list(map(int,input().split()))
print(product(x,y))
print(*product(x,y))

1 2
3 4
(1, 3) (1, 4) (2, 3) (2, 4)


In [101]:
from itertools import permutations 
s,l=input().split()
l1=list(permutations(s,int(l)))
for st in sorted(l1):
    print(*st,sep=" ") 
    
print("OR")

for st in sorted(permutations(s,int(l))):
    print(*st,sep=" ") 

HACK 2
A C
A H
A K
C A
C H
C K
H A
H C
H K
K A
K C
K H
OR
A C
A H
A K
C A
C H
C K
H A
H C
H K
K A
K C
K H


In [105]:
from itertools import combinations # this return r length subsequences
s,l=input().split()
for st in list(combinations(s,int(l))):
    print(*st,sep=" ") 
    

HACK 2
H A
H C
H K
A C
A K
C K


In [103]:
s,l=input().split()
for i in range(1,int(l)+1):
    l1=list(combinations(sorted(s),int(i)))
    for i in sorted(l1):
        print(*i,sep=" ")

HACK 2
A
C
H
K
A C
A H
A K
C H
C K
H K


In [104]:
from itertools import combinations_with_replacement as cwr
for i in list(cwr(sorted(s),int(l))):
    print(*i,sep=" ")

A A
A C
A H
A K
C C
C H
C K
H H
H K
K K


In [119]:
#Collection
from collections import Counter
mylist=[]
mylist.extend("fdftuipopitrtedxfhcvlh;joutytfcvhjbxzsaqazzaqwertyuikjhbvfcdxscvbnmmlpoiuytfredwazxcvbhnjmk")
cc=Counter(mylist)

print(cc.items)
print(cc.keys())
print(cc.values())
print(cc)

<built-in method items of Counter object at 0x7f6adc0ec570>
dict_keys(['f', 'd', 't', 'u', 'i', 'p', 'o', 'r', 'e', 'x', 'h', 'c', 'v', 'l', ';', 'j', 'y', 'b', 'z', 's', 'a', 'q', 'w', 'k', 'n', 'm'])
dict_values([6, 4, 7, 4, 4, 3, 3, 3, 3, 4, 5, 5, 5, 2, 1, 4, 3, 4, 4, 2, 4, 2, 2, 2, 2, 3])
Counter({'t': 7, 'f': 6, 'h': 5, 'c': 5, 'v': 5, 'd': 4, 'u': 4, 'i': 4, 'x': 4, 'j': 4, 'b': 4, 'z': 4, 'a': 4, 'p': 3, 'o': 3, 'r': 3, 'e': 3, 'y': 3, 'm': 3, 'l': 2, 's': 2, 'q': 2, 'w': 2, 'k': 2, 'n': 2, ';': 1})


In [ ]:
# Show shop question
n_shoes=int(input())
sizes=Counter(list(map(int,input().spit())))
total=0
for i in range(int(input())):
    size,price=list(map(int,input().split()))
    if sizes[size]:
        totol+=price
        sizes[size]-+1
print(total)

In [ ]:
# default dict
from collections import defaultdict
d=defaultdict()
n,m=map(int,input().split())
for i in range(n):
    d[input()].append(i+1)
for _ in range(m):
    m1=input()
    if m1 in d.keys():
        print(*d[m1])
    else:
        print([-1])

In [122]:
l=[]
for _ in range(int(input())):
    l.append(input())

s=Counter(l)
print(len(s))
for x in s:
    print(s[x],end=' ')

4
ab
abcd
bcdefg
ab
3
2 1 1 

In [125]:
# Banner Name
s=input()
c=Counter(sorted(s))
for i,j in c.most_common(3):
    print(i,j)

sxcykuhlkbbbbbbggdtdfuvkjjjjjjjj
j 8
b 6
k 3
